### ISSUE TITLE
To-Do/Backlog

### ISSUE THREAD

**Issue by Hgjnnf** [Hgjnnf/Template2PDF#7]
- [x] UI Cleanup (logo, website title, symmetric UI, no whitespace)
- [x] Add readme

Backlog:
- [ ] Deployment
- [ ] Add unit tests
- [ ] Basic CI/CD using GHA (CI: ESLint + Running Tests; CD: Auto Deploy)
- [ ] Improved responsive UI
- [ ] Template "store" (user can use predefined templates)
